-- DePOS Dosis - aplicar en el SQL Editor de Supabase (idempotente)

-- ===================== 0001_init.sql =====================
-- DePOS Dosis — esquema inicial (Supabase / Postgres)
-- Port fiel del esquema SQLite de backend/src/db.js (migraciones ya aplicadas)

create extension if not exists pg_trgm;

-- ============================================================
-- NÚCLEO
-- ============================================================

create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  usuario text not null unique,
  password text not null,
  rol text not null check (rol in ('admin','empleado','encargado','mesero','cocina')),
  departamentos_precios jsonb not null default '[]'::jsonb
);

create table if not exists departamentos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text not null default ''
);

create table if not exists configuracion (
  id smallint primary key default 1 check (id = 1),
  tasa_cambio double precision not null
);

create table if not exists productos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  precio_usd double precision not null,
  precio_mayor_usd double precision not null default 0,
  precio_costo double precision not null default 0,
  tipo text not null check (tipo in ('peso','unidad','variable')),
  stock double precision not null default 0,
  departamento_id bigint references departamentos(id),
  es_receta boolean not null default false,
  margen_ganancia double precision not null default 0
);

create table if not exists productos_codigos (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  codigo text not null unique
);

create table if not exists mesas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists vendedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cedula text not null unique,
  comision_porcentaje double precision not null default 0,
  activo boolean not null default true,
  usuario_id bigint references usuarios(id)
);

create table if not exists ingredientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  unidad text not null default 'kg',
  stock_actual double precision not null default 0,
  stock_minimo double precision not null default 0,
  precio_unitario double precision not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists receta_ingredientes (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  ingrediente_id bigint not null references ingredientes(id) on delete cascade,
  cantidad double precision not null default 0,
  unique (producto_id, ingrediente_id)
);

-- ============================================================
-- RESTAURANTE / PEDIDOS
-- ============================================================

create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  mesa_id bigint not null references mesas(id),
  estado text not null default 'pendiente' check (estado in ('pendiente','preparando','listo','facturado')),
  notas text not null default '',
  usuario_id bigint not null references usuarios(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cliente text not null default '',
  cancelado boolean not null default false,
  pagado boolean not null default false,
  vendedor_id bigint references vendedores(id)
);

create table if not exists pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos(id) on delete cascade,
  producto_id bigint not null references productos(id),
  cantidad integer not null default 1,
  precio_usd double precision not null,
  subtotal double precision not null,
  notas text not null default '',
  created_at timestamptz not null default now()
);

-- ============================================================
-- VENTAS / COBROS
-- ============================================================

create table if not exists ventas (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  total_usd double precision not null,
  total_bs double precision not null,
  metodo_pago text not null default 'Efectivo USD',
  referencia text not null default '',
  pagada boolean not null default true,
  usuario_id bigint not null references usuarios(id),
  vendedor_id bigint references vendedores(id),
  pedido_id bigint references pedidos(id)
);

create table if not exists detalle_venta (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references ventas(id) on delete cascade,
  producto_id bigint not null references productos(id),
  cantidad double precision not null,
  precio_usd double precision not null,
  precio_costo double precision not null default 0,
  subtotal double precision not null
);

create table if not exists venta_pagos (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references ventas(id) on delete cascade,
  metodo_pago text not null,
  monto_usd double precision not null,
  monto_bs double precision not null default 0,
  referencia text not null default ''
);

-- ============================================================
-- CRÉDITOS A CLIENTES
-- ============================================================

create table if not exists clientes_credito (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cedula text not null unique,
  deuda_total double precision not null default 0
);

create table if not exists credito_ventas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes_credito(id) on delete cascade,
  venta_id bigint not null unique references ventas(id) on delete cascade
);

create table if not exists credito_pagos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes_credito(id) on delete cascade,
  monto_usd double precision not null,
  fecha timestamptz not null default now()
);

-- ============================================================
-- PROVEEDORES
-- ============================================================

create table if not exists proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  contacto text not null default '',
  telefono text not null default '',
  direccion text not null default '',
  notas text not null default '',
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists facturas_proveedor (
  id bigint generated by default as identity primary key,
  proveedor_id bigint not null references proveedores(id) on delete cascade,
  numero_factura text not null default '',
  monto_total double precision not null default 0,
  descripcion text not null default '',
  fecha_registro timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists pagos_proveedor (
  id bigint generated by default as identity primary key,
  factura_proveedor_id bigint not null references facturas_proveedor(id) on delete cascade,
  monto double precision not null default 0,
  fecha_pago timestamptz not null default now(),
  notas text not null default '',
  created_at timestamptz not null default now()
);

-- ============================================================
-- ÍNDICES (rendimiento)
-- ============================================================

create index if not exists idx_productos_departamento on productos(departamento_id);
create index if not exists idx_productos_nombre_trgm on productos using gin (nombre gin_trgm_ops);
create index if not exists idx_productos_codigo_trgm on productos using gin (codigo gin_trgm_ops);
create index if not exists idx_productos_codigos_producto on productos_codigos(producto_id);

create index if not exists idx_pedidos_estado on pedidos(estado) where not cancelado;
create index if not exists idx_pedidos_mesa on pedidos(mesa_id);
create index if not exists idx_pedidos_created on pedidos(created_at desc);
create index if not exists idx_pedidos_vendedor on pedidos(vendedor_id);
create index if not exists idx_pedido_items_pedido on pedido_items(pedido_id);
create index if not exists idx_pedido_items_producto on pedido_items(producto_id);

create index if not exists idx_ventas_fecha on ventas(fecha desc);
create index if not exists idx_ventas_usuario on ventas(usuario_id);
create index if not exists idx_ventas_pedido on ventas(pedido_id);
create index if not exists idx_ventas_vendedor on ventas(vendedor_id);
create index if not exists idx_detalle_venta_venta on detalle_venta(venta_id);
create index if not exists idx_detalle_venta_producto on detalle_venta(producto_id);
create index if not exists idx_venta_pagos_venta on venta_pagos(venta_id);

create index if not exists idx_credito_ventas_cliente on credito_ventas(cliente_id);
create index if not exists idx_credito_pagos_cliente on credito_pagos(cliente_id);

create index if not exists idx_facturas_prov_proveedor on facturas_proveedor(proveedor_id);
create index if not exists idx_pagos_prov_factura on pagos_proveedor(factura_proveedor_id);

create index if not exists idx_receta_ing_ingrediente on receta_ingredientes(ingrediente_id);
create index if not exists idx_vendedores_usuario on vendedores(usuario_id);

-- ============================================================
-- SEGURIDAD: RLS habilitado sin políticas = denegar todo a
-- anon/authenticated. El service_role lo omite (bypass).
-- Solo el servidor (Next.js) accede con service_role.
-- ============================================================

alter table usuarios enable row level security;
alter table departamentos enable row level security;
alter table configuracion enable row level security;
alter table productos enable row level security;
alter table productos_codigos enable row level security;
alter table mesas enable row level security;
alter table vendedores enable row level security;
alter table ingredientes enable row level security;
alter table receta_ingredientes enable row level security;
alter table pedidos enable row level security;
alter table pedido_items enable row level security;
alter table ventas enable row level security;
alter table detalle_venta enable row level security;
alter table venta_pagos enable row level security;
alter table clientes_credito enable row level security;
alter table credito_ventas enable row level security;
alter table credito_pagos enable row level security;
alter table proveedores enable row level security;
alter table facturas_proveedor enable row level security;
alter table pagos_proveedor enable row level security;

-- Zona horaria del negocio (Venezuela, sin horario de verano)
alter database postgres set timezone to 'America/Caracas';


-- ===================== 0002_pedidos_ventas.sql =====================
-- DePOS Dosis — funciones transaccionales de pedidos y ventas
-- (equivalen a las db.transaction() del Express original)

-- Cantidades fraccionadas (productos por peso): SQLite las aceptaba por type affinity
alter table pedido_items alter column cantidad type double precision using cantidad::double precision;

-- ============================================================
-- Crear pedido + items en una sola transacción
-- ============================================================
create or replace function crear_pedido(
  p_mesa_id bigint,
  p_notas text,
  p_cliente text,
  p_usuario_id bigint,
  p_vendedor_id bigint,
  p_estado text,
  p_items jsonb
) returns bigint
language plpgsql
as $$
declare
  v_id bigint;
  it jsonb;
begin
  insert into pedidos (mesa_id, notas, cliente, usuario_id, vendedor_id, estado)
  values (p_mesa_id, coalesce(p_notas, ''), coalesce(p_cliente, ''), p_usuario_id, p_vendedor_id, p_estado)
  returning id into v_id;

  for it in select * from jsonb_array_elements(p_items) loop
    insert into pedido_items (pedido_id, producto_id, cantidad, precio_usd, subtotal, notas)
    values (
      v_id,
      (it->>'producto_id')::bigint,
      (it->>'cantidad')::double precision,
      (it->>'precio_usd')::double precision,
      (it->>'subtotal')::double precision,
      coalesce(it->>'notas', '')
    );
  end loop;

  return v_id;
end;
$$;

-- ============================================================
-- Agregar items a un pedido existente
-- ============================================================
create or replace function agregar_items_pedido(
  p_pedido_id bigint,
  p_items jsonb
) returns void
language plpgsql
as $$
declare
  it jsonb;
begin
  for it in select * from jsonb_array_elements(p_items) loop
    insert into pedido_items (pedido_id, producto_id, cantidad, precio_usd, subtotal, notas)
    values (
      p_pedido_id,
      (it->>'producto_id')::bigint,
      (it->>'cantidad')::double precision,
      (it->>'precio_usd')::double precision,
      (it->>'subtotal')::double precision,
      coalesce(it->>'notas', '')
    );
  end loop;

  update pedidos set updated_at = now() where id = p_pedido_id;
end;
$$;

-- ============================================================
-- Quitar un item de un pedido (delete + updated_at atómicos)
-- ============================================================
create or replace function pedido_quitar_item(
  p_pedido_id bigint,
  p_item_id bigint
) returns boolean
language plpgsql
as $$
declare
  v_count bigint;
begin
  delete from pedido_items where id = p_item_id and pedido_id = p_pedido_id;
  get diagnostics v_count = row_count;
  if v_count = 0 then
    return false;
  end if;
  update pedidos set updated_at = now() where id = p_pedido_id;
  return true;
end;
$$;

-- ============================================================
-- Crear venta completa (transacción del POST /api/ventas):
-- venta + detalle + descuento de ingredientes (recetas) +
-- crédito + multipago + marca pedido pagado
-- ============================================================
create or replace function crear_venta(
  p_total_usd double precision,
  p_total_bs double precision,
  p_metodo_pago text,
  p_referencia text,
  p_pagada boolean,
  p_usuario_id bigint,
  p_pedido_id bigint,
  p_cliente_id bigint,
  p_items jsonb,
  p_pagos jsonb
) returns bigint
language plpgsql
as $$
declare
  v_venta_id bigint;
  it jsonb;
  v_pid bigint;
  v_costo double precision;
  v_es_receta boolean;
  r record;
  v_resta double precision;
  v_tasa double precision;
  p jsonb;
  v_monto_bs double precision;
  v_estado text;
begin
  insert into ventas (total_usd, total_bs, metodo_pago, referencia, pagada, usuario_id, pedido_id)
  values (p_total_usd, p_total_bs, p_metodo_pago, coalesce(p_referencia, ''), p_pagada, p_usuario_id, p_pedido_id)
  returning id into v_venta_id;

  -- Detalle + descuento de ingredientes de recetas
  for it in select * from jsonb_array_elements(p_items) loop
    v_pid := (it->>'producto_id')::bigint;

    select coalesce(precio_costo, 0), coalesce(es_receta, false)
      into v_costo, v_es_receta
      from productos where id = v_pid;

    insert into detalle_venta (venta_id, producto_id, cantidad, precio_usd, precio_costo, subtotal)
    values (
      v_venta_id,
      v_pid,
      (it->>'cantidad')::double precision,
      (it->>'precio_usd')::double precision,
      coalesce(v_costo, 0),
      (it->>'subtotal')::double precision
    );

    if coalesce(v_es_receta, false) then
      for r in
        select ri.ingrediente_id, ri.cantidad, i.stock_actual
        from receta_ingredientes ri
        join ingredientes i on i.id = ri.ingrediente_id
        where ri.producto_id = v_pid
      loop
        v_resta := round((r.cantidad * (it->>'cantidad')::double precision)::numeric, 3)::double precision;
        update ingredientes
        set stock_actual = greatest(0, round((r.stock_actual - v_resta)::numeric, 3)::double precision)
        where id = r.ingrediente_id;
      end loop;
    end if;
  end loop;

  -- Crédito: registrar venta a crédito y aumentar deuda
  if p_cliente_id is not null then
    insert into credito_ventas (cliente_id, venta_id) values (p_cliente_id, v_venta_id);
    update clientes_credito
    set deuda_total = round((deuda_total + round(p_total_usd::numeric, 2))::numeric, 2)::double precision
    where id = p_cliente_id;
  end if;

  -- Pagos (multipago) o pago móvil con referencia
  v_tasa := case when p_total_usd > 0 then p_total_bs / p_total_usd else 0 end;

  if p_pagos is not null and jsonb_array_length(p_pagos) > 0 then
    for p in select * from jsonb_array_elements(p_pagos) loop
      v_monto_bs := round(((p->>'monto_usd')::double precision * v_tasa)::numeric, 2)::double precision;
      insert into venta_pagos (venta_id, metodo_pago, monto_usd, monto_bs, referencia)
      values (
        v_venta_id,
        p->>'metodo_pago',
        (p->>'monto_usd')::double precision,
        v_monto_bs,
        coalesce(p->>'referencia', '')
      );
    end loop;
  elsif p_metodo_pago = 'Pago Móvil' and coalesce(p_referencia, '') <> '' then
    v_monto_bs := round((p_total_usd * v_tasa)::numeric, 2)::double precision;
    insert into venta_pagos (venta_id, metodo_pago, monto_usd, monto_bs, referencia)
    values (v_venta_id, 'Pago Móvil', p_total_usd, v_monto_bs, p_referencia);
  end if;

  -- Marcar pedido como pagado (y facturado si estaba listo)
  if p_pedido_id is not null then
    select estado into v_estado from pedidos where id = p_pedido_id;
    if v_estado = 'listo' then
      update pedidos set estado = 'facturado', pagado = true, updated_at = now() where id = p_pedido_id;
    else
      update pedidos set pagado = true, updated_at = now() where id = p_pedido_id;
    end if;
  end if;

  return v_venta_id;
end;
$$;

-- ============================================================
-- Buscar pedidos (GET /api/pedidos/buscar?q=) con la misma
-- lógica SQL del original: CAST(id AS TEXT) LIKE o mesa LIKE
-- ============================================================
create or replace function pedidos_buscar_json(p_q text)
returns jsonb
language sql
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', p.id,
        'mesa_id', p.mesa_id,
        'estado', p.estado,
        'notas', p.notas,
        'usuario_id', p.usuario_id,
        'created_at', p.created_at,
        'updated_at', p.updated_at,
        'cliente', p.cliente,
        'cancelado', p.cancelado,
        'pagado', p.pagado,
        'vendedor_id', p.vendedor_id,
        'mesa_nombre', m.nombre,
        'usuario_nombre', u.usuario,
        'vendedor_nombre', v.nombre,
        'items', coalesce((
          select jsonb_agg(
            jsonb_build_object(
              'id', pi.id,
              'pedido_id', pi.pedido_id,
              'producto_id', pi.producto_id,
              'cantidad', pi.cantidad,
              'precio_usd', pi.precio_usd,
              'subtotal', pi.subtotal,
              'notas', pi.notas,
              'created_at', pi.created_at,
              'producto_nombre', pr.nombre
            ) order by pi.id
          )
          from pedido_items pi
          join productos pr on pr.id = pi.producto_id
          where pi.pedido_id = p.id
        ), '[]'::jsonb)
      )
      order by p.updated_at desc
    ),
    '[]'::jsonb
  )
  from pedidos p
  join mesas m on m.id = p.mesa_id
  join usuarios u on u.id = p.usuario_id
  left join vendedores v on v.id = p.vendedor_id
  where p.cancelado = false
    and (cast(p.id as text) like '%' || p_q || '%' or m.nombre like '%' || p_q || '%')
  limit 20;
$$;


-- ===================== 0011_reportes.sql =====================
-- Reportes: funciones RPC con las agregaciones (SUM / GROUP BY) del backend Express original.
-- Todas reciben rango opcional (null = sin filtro de fecha), salvo reporte_cobertura (obligatorio).

create or replace function reporte_ventas_totales(p_from timestamptz default null, p_to timestamptz default null)
returns jsonb
language sql
stable
as $$
with v as (
  select id, fecha, total_usd, total_bs, metodo_pago, pagada
  from ventas
  where (metodo_pago <> 'Credito' or pagada = true)
    and ((p_from is null or p_to is null) or (fecha >= p_from and fecha <= p_to))
),
dd as (
  select dv.producto_id, dv.cantidad, dv.subtotal, dv.precio_costo
  from detalle_venta dv
  join v on v.id = dv.venta_id
)
select jsonb_build_object(
  'count', (select count(*) from v),
  'total_usd', (select coalesce(sum(total_usd), 0) from v),
  'total_bs', (select coalesce(sum(total_bs), 0) from v),
  'total_unidades', (select coalesce(sum(cantidad), 0) from dd),
  'total_ganancia', (select coalesce(sum(subtotal - (precio_costo * cantidad)), 0) from dd),
  'producto_mas_vendido', (
    select jsonb_build_object('nombre', p.nombre, 'codigo', p.codigo, 'total', sum(d.cantidad))
    from dd d
    join productos p on p.id = d.producto_id
    group by d.producto_id, p.id, p.nombre, p.codigo
    order by sum(d.cantidad) desc
    limit 1
  ),
  'por_metodo_pago', coalesce(
    (
      select jsonb_agg(jsonb_build_object(
        'metodo_pago', metodo_pago,
        'count', cnt,
        'total_usd', total_usd,
        'total_bs', total_bs
      ) order by total_usd desc)
      from (
        select metodo_pago, count(*) as cnt, sum(total_usd) as total_usd, sum(total_bs) as total_bs
        from v
        group by metodo_pago
      ) t
    ),
    '[]'::jsonb
  )
)
$$;

create or replace function reporte_pagos(p_from timestamptz default null, p_to timestamptz default null)
returns jsonb
language sql
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'metodo_pago', t.metodo_pago,
        'count', t.cnt,
        'total_usd', t.total_usd,
        'total_bs', t.total_bs
      )
      order by t.total_usd desc
    ),
    '[]'::jsonb
  )
  from (
    select
      coalesce(vp.metodo_pago, v.metodo_pago) as metodo_pago,
      count(distinct v.id) as cnt,
      sum(coalesce(vp.monto_usd, v.total_usd)) as total_usd,
      sum(coalesce(vp.monto_bs, v.total_bs)) as total_bs
    from ventas v
    left join venta_pagos vp on vp.venta_id = v.id
    where (v.metodo_pago <> 'Credito' or v.pagada = true)
      and ((p_from is null or p_to is null) or (v.fecha >= p_from and v.fecha <= p_to))
    group by coalesce(vp.metodo_pago, v.metodo_pago)
    order by total_usd desc
  ) t
$$;

create or replace function reporte_ventas_por_departamento(p_from timestamptz default null, p_to timestamptz default null)
returns jsonb
language sql
stable
as $$
  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'departamento', t.departamento,
        'departamento_id', t.departamento_id,
        'total_ventas', t.total_ventas,
        'total_vendido_usd', t.total_vendido_usd,
        'total_vendido_bs', t.total_vendido_bs,
        'unidades', t.unidades
      )
      order by t.total_vendido_usd desc
    ),
    '[]'::jsonb
  )
  from (
    select
      coalesce(d.nombre, 'Sin departamento') as departamento,
      d.id as departamento_id,
      count(distinct dv.venta_id) as total_ventas,
      sum(dv.subtotal) as total_vendido_usd,
      coalesce(sum(dv.subtotal * case when v.total_usd > 0 then v.total_bs / v.total_usd else 0 end), 0) as total_vendido_bs,
      sum(dv.cantidad) as unidades
    from detalle_venta dv
    join ventas v on v.id = dv.venta_id
    join productos p on p.id = dv.producto_id
    left join departamentos d on d.id = p.departamento_id
    where (v.metodo_pago <> 'Credito' or v.pagada = true)
      and ((p_from is null or p_to is null) or (v.fecha >= p_from and v.fecha <= p_to))
    group by d.id, d.nombre
    order by total_vendido_usd desc
  ) t
$$;

create or replace function reporte_pagos_movil(p_from timestamptz default null, p_to timestamptz default null)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'pagos', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', x.id,
            'fecha', x.fecha,
            'total_usd', x.total_usd,
            'total_bs', x.total_bs,
            'referencia', x.referencia,
            'usuario_nombre', u.usuario
          )
          order by x.fecha desc
        ),
        '[]'::jsonb
      )
      from (
        select v.id, v.fecha, v.total_usd, v.total_bs, v.referencia, v.usuario_id
        from ventas v
        where v.metodo_pago = 'Pago Móvil'
          and ((p_from is null or p_to is null) or (v.fecha >= p_from and v.fecha <= p_to))
        order by v.fecha desc
        limit 200
      ) x
      left join usuarios u on u.id = x.usuario_id
    ),
    'multipago', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'id', y.id,
            'fecha', y.fecha,
            'monto_usd', y.monto_usd,
            'monto_bs', y.monto_bs,
            'referencia', y.referencia,
            'usuario_nombre', y.usuario_nombre
          )
          order by y.fecha desc
        ),
        '[]'::jsonb
      )
      from (
        select v.id, v.fecha, vp.monto_usd, vp.monto_bs, vp.referencia, u.usuario as usuario_nombre
        from venta_pagos vp
        join ventas v on v.id = vp.venta_id
        left join usuarios u on u.id = v.usuario_id
        where vp.metodo_pago = 'Pago Móvil' and v.metodo_pago = 'Multipago'
          and ((p_from is null or p_to is null) or (v.fecha >= p_from and v.fecha <= p_to))
        order by v.fecha desc
        limit 200
      ) y
    )
  )
$$;

create or replace function reporte_cobertura(p_from timestamptz, p_to timestamptz)
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    'total_ganancia', (
      select coalesce(sum(dv.subtotal - (dv.precio_costo * dv.cantidad)), 0)
      from detalle_venta dv
      join ventas v on v.id = dv.venta_id
      where (v.metodo_pago <> 'Credito' or v.pagada = true)
        and v.fecha >= p_from and v.fecha <= p_to
    ),
    'proveedores', (
      select coalesce(
        jsonb_agg(
          jsonb_build_object(
            'proveedor_id', t.proveedor_id,
            'proveedor_nombre', t.proveedor_nombre,
            'total_facturado', t.total_facturado,
            'total_pagado', t.total_pagado,
            'saldo_pendiente', t.saldo_pendiente
          )
          order by t.saldo_pendiente desc
        ),
        '[]'::jsonb
      )
      from (
        select
          p.id as proveedor_id,
          p.nombre as proveedor_nombre,
          coalesce(sum(fp.monto_total), 0) as total_facturado,
          coalesce(sum(pg_sub.total_pagado), 0) as total_pagado,
          (coalesce(sum(fp.monto_total), 0) - coalesce(sum(pg_sub.total_pagado), 0)) as saldo_pendiente
        from proveedores p
        left join facturas_proveedor fp on fp.proveedor_id = p.id
        left join (
          select factura_proveedor_id, sum(monto) as total_pagado
          from pagos_proveedor
          group by factura_proveedor_id
        ) pg_sub on pg_sub.factura_proveedor_id = fp.id
        where p.activo = true
        group by p.id, p.nombre
        having (coalesce(sum(fp.monto_total), 0) - coalesce(sum(pg_sub.total_pagado), 0)) > 0
        order by saldo_pendiente desc
      ) t
    )
  )
$$;


-- ===================== 0012_creditos.sql =====================
-- ============================================================
-- 0012 — CRÉDITOS (FIADO)
-- Port transaccional de los endpoints de créditos.
-- El original (better-sqlite3) usaba db.transaction(...); en
-- Postgres con PostgREST eso se replica con funciones RPC.
-- ============================================================

-- ------------------------------------------------------------
-- POST /api/creditos/:id/pagar
-- Descuenta la deuda, registra el pago, crea la venta de cobro
-- (+ venta_pagos) e inserta detalle_venta proporcional para que
-- los reportes de ganancia incluyan el cobro.
-- ------------------------------------------------------------
create or replace function public.pagar_credito(
  p_cliente_id bigint,
  p_monto double precision,
  p_metodo_pago text,
  p_venta_referencia text,
  p_pago_referencia text,
  p_total_bs double precision,
  p_usuario_id bigint
) returns bigint
language plpgsql
set search_path = public
as $$
declare
  v_deuda double precision;
  v_total_original double precision := 0;
  v_proporcion double precision := 0;
  v_venta_id bigint;
  item record;
begin
  -- El cliente se bloquea para evitar pagos concurrentes (anti OVERPAY)
  select deuda_total into v_deuda
    from clientes_credito
   where id = p_cliente_id
     for update;
  if not found then
    raise exception 'NOT_FOUND';
  end if;
  if p_monto > v_deuda + 0.001 then
    raise exception 'OVERPAY';
  end if;

  -- Proporción de ganancia: se calcula ANTES de insertar la nueva venta,
  -- igual que el original (creditVentas se leía antes del tx).
  select coalesce(sum(v.total_usd), 0)
    into v_total_original
    from credito_ventas cv
    join ventas v on v.id = cv.venta_id
   where cv.cliente_id = p_cliente_id
     and v.metodo_pago = 'Credito';

  if v_total_original > 0 then
    v_proporcion := p_monto / v_total_original;
  end if;

  update clientes_credito
     set deuda_total = round((deuda_total - p_monto)::numeric, 2)::double precision
   where id = p_cliente_id;

  insert into credito_pagos (cliente_id, monto_usd, fecha)
  values (p_cliente_id, p_monto, now());

  insert into ventas (fecha, total_usd, total_bs, metodo_pago, referencia, pagada, usuario_id)
  values (now(), p_monto, p_total_bs, p_metodo_pago, p_venta_referencia, true, p_usuario_id)
  returning id into v_venta_id;

  -- Pago en venta_pagos para los reportes por método de pago
  insert into venta_pagos (venta_id, metodo_pago, monto_usd, monto_bs, referencia)
  values (v_venta_id, p_metodo_pago, p_monto, p_total_bs, p_pago_referencia);

  -- Detalle proporcional para ganancia en reportes
  if v_proporcion > 0 then
    for item in
      select dv.producto_id, dv.cantidad, dv.precio_usd, dv.precio_costo, dv.subtotal
        from credito_ventas cv
        join ventas v on v.id = cv.venta_id
        join detalle_venta dv on dv.venta_id = cv.venta_id
       where cv.cliente_id = p_cliente_id
         and v.metodo_pago = 'Credito'
    loop
      insert into detalle_venta (venta_id, producto_id, cantidad, precio_usd, precio_costo, subtotal)
      values (v_venta_id, item.producto_id,
              item.cantidad * v_proporcion,
              item.precio_usd,
              item.precio_costo,
              item.subtotal * v_proporcion);
    end loop;
  end if;

  return v_venta_id;
end;
$$;

-- ------------------------------------------------------------
-- DELETE /api/creditos/:id
-- Borra pagos → ventas de crédito → cliente (en transacción).
-- ------------------------------------------------------------
create or replace function public.eliminar_cliente_credito(p_cliente_id bigint)
returns void
language plpgsql
set search_path = public
as $$
begin
  if not exists (select 1 from clientes_credito where id = p_cliente_id) then
    raise exception 'NOT_FOUND';
  end if;

  delete from credito_pagos where cliente_id = p_cliente_id;
  delete from credito_ventas where cliente_id = p_cliente_id;
  delete from clientes_credito where id = p_cliente_id;
end;
$$;


-- ===================== 0013_facturas.sql =====================
-- ============================================================
-- 0013 — FACTURAS (edición de ventas)
-- Port transaccional de los endpoints de edición de facturas.
-- El original (better-sqlite3) usaba db.transaction(...); en
-- Postgres con PostgREST eso se replica con funciones RPC.
-- ============================================================

-- El original (SQLite con tipado dinámico) aceptaba cantidades
-- fraccionadas en pedido_items (productos vendidos por peso).
-- Postgres rechazaría el cast double precision → integer.
alter table pedido_items
  alter column cantidad type double precision using cantidad::double precision;

-- ------------------------------------------------------------
-- POST /api/facturas/:id/items
-- Agrega un ítem, recalcula totales, ajusta la deuda del cliente
-- si la venta es a crédito y replica el ítem en el pedido.
-- ------------------------------------------------------------
create or replace function public.factura_agregar_item(
  p_venta_id bigint,
  p_producto_id bigint,
  p_cantidad double precision,
  p_precio_usd double precision,
  p_subtotal double precision,
  p_precio_costo double precision,
  p_tasa double precision
) returns void
language plpgsql
set search_path = public
as $$
declare
  v_venta ventas%rowtype;
  v_total double precision;
  v_total_bs double precision;
  v_cliente_id bigint;
  v_diff double precision;
begin
  select * into v_venta from ventas where id = p_venta_id;
  if not found then
    raise exception 'VENTA_NOT_FOUND';
  end if;
  if not exists (select 1 from productos where id = p_producto_id) then
    raise exception 'PRODUCT_NOT_FOUND';
  end if;

  insert into detalle_venta (venta_id, producto_id, cantidad, precio_usd, precio_costo, subtotal)
  values (p_venta_id, p_producto_id, p_cantidad, p_precio_usd, p_precio_costo, p_subtotal);

  select coalesce(sum(subtotal), 0) into v_total
    from detalle_venta
   where venta_id = p_venta_id;

  v_total := round(v_total::numeric, 2)::double precision;
  v_total_bs := round((v_total * p_tasa)::numeric, 2)::double precision;

  update ventas set total_usd = v_total, total_bs = v_total_bs where id = p_venta_id;

  if v_venta.metodo_pago = 'Credito' then
    select cliente_id into v_cliente_id from credito_ventas where venta_id = p_venta_id;
    if found then
      v_diff := round((v_total - v_venta.total_usd)::numeric, 2)::double precision;
      if v_diff > 0 then
        update clientes_credito
           set deuda_total = round((deuda_total + v_diff)::numeric, 2)::double precision
         where id = v_cliente_id;
      end if;
    end if;
  end if;

  if v_venta.pedido_id is not null then
    insert into pedido_items (pedido_id, producto_id, cantidad, precio_usd, subtotal, notas, created_at)
    values (v_venta.pedido_id, p_producto_id, p_cantidad, p_precio_usd, p_subtotal, '', now());
  end if;
end;
$$;

-- ------------------------------------------------------------
-- DELETE /api/facturas/:id/items/:itemId
-- Quita un ítem, recalcula totales; si la venta queda vacía la
-- elimina (con sus pagos y su vínculo de crédito), si no ajusta
-- la deuda del cliente cuando es a crédito.
-- ------------------------------------------------------------
create or replace function public.factura_quitar_item(
  p_venta_id bigint,
  p_item_id bigint,
  p_tasa double precision
) returns void
language plpgsql
set search_path = public
as $$
declare
  v_venta ventas%rowtype;
  v_total double precision;
  v_total_bs double precision;
  v_cliente_id bigint;
  v_diff double precision;
begin
  select * into v_venta from ventas where id = p_venta_id;
  if not found then
    raise exception 'VENTA_NOT_FOUND';
  end if;
  if not exists (select 1 from detalle_venta where id = p_item_id and venta_id = p_venta_id) then
    raise exception 'ITEM_NOT_FOUND';
  end if;

  delete from detalle_venta where id = p_item_id;

  select coalesce(sum(subtotal), 0) into v_total
    from detalle_venta
   where venta_id = p_venta_id;

  v_total := round(v_total::numeric, 2)::double precision;
  v_total_bs := round((v_total * p_tasa)::numeric, 2)::double precision;

  if v_total <= 0 then
    delete from detalle_venta where venta_id = p_venta_id;
    delete from venta_pagos where venta_id = p_venta_id;
    delete from credito_ventas where venta_id = p_venta_id;
    delete from ventas where id = p_venta_id;
  else
    update ventas set total_usd = v_total, total_bs = v_total_bs where id = p_venta_id;

    if v_venta.metodo_pago = 'Credito' then
      select cliente_id into v_cliente_id from credito_ventas where venta_id = p_venta_id;
      if found then
        v_diff := round((v_venta.total_usd - v_total)::numeric, 2)::double precision;
        if v_diff > 0 then
          update clientes_credito
             set deuda_total = round((deuda_total - v_diff)::numeric, 2)::double precision
           where id = v_cliente_id;
        end if;
      end if;
    end if;
  end if;
end;
$$;


-- ===================== 0014_recetas.sql =====================
-- Port de la transacción de PUT /api/recetas/:productoId (backend/src/server.js):
--   db.transaction(() => { DELETE FROM receta_ingredientes WHERE producto_id = ?;
--                          INSERT ... por cada ingrediente con cantidad > 0 })
-- El handler lo invoca vía: supabaseAdmin().rpc('replace_receta', { p_producto_id, p_items })

create or replace function public.replace_receta(p_producto_id bigint, p_items jsonb)
returns void
language plpgsql
as $$
begin
  delete from receta_ingredientes where producto_id = p_producto_id;

  insert into receta_ingredientes (producto_id, ingrediente_id, cantidad)
  select p_producto_id,
         (item ->> 'ingrediente_id')::bigint,
         (item ->> 'cantidad')::double precision
  from jsonb_array_elements(p_items) as item
  where (item ->> 'cantidad')::double precision > 0;
end;
$$;

-- Solo el service_role (backend) debe ejecutarla
revoke execute on function public.replace_receta(bigint, jsonb) from public, anon, authenticated;
grant execute on function public.replace_receta(bigint, jsonb) to service_role;


