-- DePOS Dosis — esquema inicial (Supabase / Postgres)
-- Port fiel del esquema SQLite de backend/src/db.js (migraciones ya aplicadas)

create extension if not exists pg_trgm;

-- ============================================================
-- NÚCLEO
-- ============================================================

create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  usuario text not null unique,
  password text not null,
  rol text not null check (rol in ('admin','empleado','encargado','mesero','cocina')),
  departamentos_precios jsonb not null default '[]'::jsonb
);

create table if not exists departamentos (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  descripcion text not null default ''
);

create table if not exists configuracion (
  id smallint primary key default 1 check (id = 1),
  tasa_cambio double precision not null
);

create table if not exists productos (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  nombre text not null,
  precio_usd double precision not null,
  precio_mayor_usd double precision not null default 0,
  precio_costo double precision not null default 0,
  tipo text not null check (tipo in ('peso','unidad','variable')),
  stock double precision not null default 0,
  departamento_id bigint references departamentos(id),
  es_receta boolean not null default false,
  margen_ganancia double precision not null default 0
);

create table if not exists productos_codigos (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  codigo text not null unique
);

create table if not exists mesas (
  id bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true
);

create table if not exists vendedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cedula text not null unique,
  comision_porcentaje double precision not null default 0,
  activo boolean not null default true,
  usuario_id bigint references usuarios(id)
);

create table if not exists ingredientes (
  id bigint generated by default as identity primary key,
  nombre text not null,
  unidad text not null default 'kg',
  stock_actual double precision not null default 0,
  stock_minimo double precision not null default 0,
  precio_unitario double precision not null default 0,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists receta_ingredientes (
  id bigint generated by default as identity primary key,
  producto_id bigint not null references productos(id) on delete cascade,
  ingrediente_id bigint not null references ingredientes(id) on delete cascade,
  cantidad double precision not null default 0,
  unique (producto_id, ingrediente_id)
);

-- ============================================================
-- RESTAURANTE / PEDIDOS
-- ============================================================

create table if not exists pedidos (
  id bigint generated by default as identity primary key,
  mesa_id bigint not null references mesas(id),
  estado text not null default 'pendiente' check (estado in ('pendiente','preparando','listo','facturado')),
  notas text not null default '',
  usuario_id bigint not null references usuarios(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  cliente text not null default '',
  cancelado boolean not null default false,
  pagado boolean not null default false,
  vendedor_id bigint references vendedores(id)
);

create table if not exists pedido_items (
  id bigint generated by default as identity primary key,
  pedido_id bigint not null references pedidos(id) on delete cascade,
  producto_id bigint not null references productos(id),
  cantidad integer not null default 1,
  precio_usd double precision not null,
  subtotal double precision not null,
  notas text not null default '',
  created_at timestamptz not null default now()
);

-- ============================================================
-- VENTAS / COBROS
-- ============================================================

create table if not exists ventas (
  id bigint generated by default as identity primary key,
  fecha timestamptz not null default now(),
  total_usd double precision not null,
  total_bs double precision not null,
  metodo_pago text not null default 'Efectivo USD',
  referencia text not null default '',
  pagada boolean not null default true,
  usuario_id bigint not null references usuarios(id),
  vendedor_id bigint references vendedores(id),
  pedido_id bigint references pedidos(id)
);

create table if not exists detalle_venta (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references ventas(id) on delete cascade,
  producto_id bigint not null references productos(id),
  cantidad double precision not null,
  precio_usd double precision not null,
  precio_costo double precision not null default 0,
  subtotal double precision not null
);

create table if not exists venta_pagos (
  id bigint generated by default as identity primary key,
  venta_id bigint not null references ventas(id) on delete cascade,
  metodo_pago text not null,
  monto_usd double precision not null,
  monto_bs double precision not null default 0,
  referencia text not null default ''
);

-- ============================================================
-- CRÉDITOS A CLIENTES
-- ============================================================

create table if not exists clientes_credito (
  id bigint generated by default as identity primary key,
  nombre text not null,
  cedula text not null unique,
  deuda_total double precision not null default 0
);

create table if not exists credito_ventas (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes_credito(id) on delete cascade,
  venta_id bigint not null unique references ventas(id) on delete cascade
);

create table if not exists credito_pagos (
  id bigint generated by default as identity primary key,
  cliente_id bigint not null references clientes_credito(id) on delete cascade,
  monto_usd double precision not null,
  fecha timestamptz not null default now()
);

-- ============================================================
-- PROVEEDORES
-- ============================================================

create table if not exists proveedores (
  id bigint generated by default as identity primary key,
  nombre text not null,
  contacto text not null default '',
  telefono text not null default '',
  direccion text not null default '',
  notas text not null default '',
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists facturas_proveedor (
  id bigint generated by default as identity primary key,
  proveedor_id bigint not null references proveedores(id) on delete cascade,
  numero_factura text not null default '',
  monto_total double precision not null default 0,
  descripcion text not null default '',
  fecha_registro timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists pagos_proveedor (
  id bigint generated by default as identity primary key,
  factura_proveedor_id bigint not null references facturas_proveedor(id) on delete cascade,
  monto double precision not null default 0,
  fecha_pago timestamptz not null default now(),
  notas text not null default '',
  created_at timestamptz not null default now()
);

-- ============================================================
-- ÍNDICES (rendimiento)
-- ============================================================

create index if not exists idx_productos_departamento on productos(departamento_id);
create index if not exists idx_productos_nombre_trgm on productos using gin (nombre gin_trgm_ops);
create index if not exists idx_productos_codigo_trgm on productos using gin (codigo gin_trgm_ops);
create index if not exists idx_productos_codigos_producto on productos_codigos(producto_id);

create index if not exists idx_pedidos_estado on pedidos(estado) where not cancelado;
create index if not exists idx_pedidos_mesa on pedidos(mesa_id);
create index if not exists idx_pedidos_created on pedidos(created_at desc);
create index if not exists idx_pedidos_vendedor on pedidos(vendedor_id);
create index if not exists idx_pedido_items_pedido on pedido_items(pedido_id);
create index if not exists idx_pedido_items_producto on pedido_items(producto_id);

create index if not exists idx_ventas_fecha on ventas(fecha desc);
create index if not exists idx_ventas_usuario on ventas(usuario_id);
create index if not exists idx_ventas_pedido on ventas(pedido_id);
create index if not exists idx_ventas_vendedor on ventas(vendedor_id);
create index if not exists idx_detalle_venta_venta on detalle_venta(venta_id);
create index if not exists idx_detalle_venta_producto on detalle_venta(producto_id);
create index if not exists idx_venta_pagos_venta on venta_pagos(venta_id);

create index if not exists idx_credito_ventas_cliente on credito_ventas(cliente_id);
create index if not exists idx_credito_pagos_cliente on credito_pagos(cliente_id);

create index if not exists idx_facturas_prov_proveedor on facturas_proveedor(proveedor_id);
create index if not exists idx_pagos_prov_factura on pagos_proveedor(factura_proveedor_id);

create index if not exists idx_receta_ing_ingrediente on receta_ingredientes(ingrediente_id);
create index if not exists idx_vendedores_usuario on vendedores(usuario_id);

-- ============================================================
-- SEGURIDAD: RLS habilitado sin políticas = denegar todo a
-- anon/authenticated. El service_role lo omite (bypass).
-- Solo el servidor (Next.js) accede con service_role.
-- ============================================================

alter table usuarios enable row level security;
alter table departamentos enable row level security;
alter table configuracion enable row level security;
alter table productos enable row level security;
alter table productos_codigos enable row level security;
alter table mesas enable row level security;
alter table vendedores enable row level security;
alter table ingredientes enable row level security;
alter table receta_ingredientes enable row level security;
alter table pedidos enable row level security;
alter table pedido_items enable row level security;
alter table ventas enable row level security;
alter table detalle_venta enable row level security;
alter table venta_pagos enable row level security;
alter table clientes_credito enable row level security;
alter table credito_ventas enable row level security;
alter table credito_pagos enable row level security;
alter table proveedores enable row level security;
alter table facturas_proveedor enable row level security;
alter table pagos_proveedor enable row level security;

-- Zona horaria del negocio (Venezuela, sin horario de verano)
alter database postgres set timezone to 'America/Caracas';
